### ISSUE TITLE
dinat does not work well with English version

### ISSUE THREAD

**Issue by thomsmits** [informatik-mannheim/thesis-template#12]
From an E-Mail:

ich verwende aktuell Ihre Latex-Vorlage für eine Studienarbeit bei Prof.
XXXX. Da ich diese Studienarbeit auf Englisch verfasse, habe ich
entsprechend den Vorgaben die Variable in der Datei "docinfo.tex" von
"de" auf "en" gesetzt. Das funktioniert auch soweit sehr gut, ausser bei
dem Quellenverzeichnis. Dort nutzen Sie die Bibliothek "dinat", die
(wenn ich das richtig verstanden habe) entsprechend die Ausgabe auf
Deutsch erstellt. Das bedeutet, dass bei mehreren Autoren z.B. "u. a."
oder bei Internetquellen "Zugriffsdatum" ergänzt wird.

**Comment by Exiver** [comment]
Vielen Dank ;-)
