### ISSUE TITLE
Undefined control sequence. Im titelblatt.tex

### ISSUE THREAD

**Issue by lenuyx** [informatik-mannheim/thesis-template#17]
Sharelatex zeigt mir diesen Fehler an.
```
\ifthenelse{\equal{\hsmasprache}{de}}%
{\hsmabibde \\ \vspace{0.5cm} \\ \hsmabiben}
{\hsmabiben \\ \vspace{0.5cm} \\ \hsmabibde}
```
<img width="772" alt="image" src="https://cloud.githubusercontent.com/assets/9435598/26684660/d6449600-46e7-11e7-9935-c34723e8fc7e.png">

**Comment by thomsmits** [comment]
Ich kann den Fehler nicht reproduzieren:

- Projekt als ZIP in ShareLatex hochgeladen
- Main Document auf "thesis.tex" gesetzt.
- Recompile gedrückt

Es kommt keine Fehlermeldung, sondern ein korrektes PDF heraus.

<img width="243" alt="sharelatex" src="https://cloud.githubusercontent.com/assets/197846/26691202/8f26e682-46fc-11e7-9906-91d10b9786a6.png">

**Comment by lenuyx** [comment]
Ok hab den Fehler gefunden. Hatte die Zeile des Englischen Hochschulnamen auskommentiert. Danke.
