### ISSUE TITLE
Einrückung des Titels auf dem Deckblatt

### ISSUE THREAD

**Issue by gosua** [informatik-mannheim/thesis-template#18]
Auf den ersten Blick sieht die Einrückung des Titels/Namen auf dem Deckblatt etwas merkwürdig aus. Ist das so gewollt, um die [vorgegebenen Abstände der Druckerei ](https://www.tbl.hs-mannheim.de/fileadmin/user_upload/einrichtungen/tbl/1-Dokumente/Deckblatt_Einband_HS_Mannheim.pdf)einzuhalten? Laut Kommentar in `docinfo.tex` soll man in `titelblatt.tex` nichts mehr ändern.

![image](https://user-images.githubusercontent.com/2049002/27260074-50259b5c-5423-11e7-82f6-fe290862b197.png)

**Comment by thomsmits** [comment]
Das Deckblatt des Template wurde speziell für die Hochschule und deren Umschläge entwickelt. Leider ist das Fenster des Umschlages aber nicht in der Mitte, sondern leicht nach rechts versetzt. Damit der Titel und Autor korrekt in das Fenster passen, sind sie nicht auf der Seite zentriert, sondern manuell positioniert.

Kurz zusammengefasst: It`s not a bug, it`s a feature.

Wenn Sie die Arbeit nicht in den offiziellen Umschlag binden lassen wollen, können Sie natürlich gerne das Titelblatt verändern und den Titel und Autor korrekt zentrieren.

**Comment by tihme** [comment]
Am 18.06.2017 um 12:42 schrieb Thomas Smits:
> Das Deckblatt des Template wurde speziell für die Hochschule und deren
> Umschläge entwickelt. Leider ist das Fenster des Umschlages aber nicht in der
> Mitte, sondern leicht nach rechts versetzt. Damit der Titel und Autor korrekt
> in das Fenster passen, sind sie nicht auf der Seite zentriert, sondern manuell
> positioniert.
> 
> Kurz zusammengefasst: It|s not a bug, it|s a feature.

Dieses Feature ist ein Bug. Ich bin dafür, diesen Bug zu korrigieren und
- entweder passend zum Sichtfenster zu zentrieren oder
- passend zum Fenster linksbündig zu setzen.
Letzteres wäre ein etwas größerer Designwechsel.
