### ISSUE TITLE
Red text when enabling the new option "hsmasperrvermerk"

### ISSUE THREAD

**Issue by Arwany** [informatik-mannheim/thesis-template#2]
Hi,

the entire text of the document will be in red starting from the word "Sperrvermerk". Once this option set to false, the text will get back to normal black.

Is it a desired format, or a bug?

Thank you for this amazing template, it has saved me HUGE time.

**Comment by thomsmits** [comment]
Tanks for the feedback. Its obviously a bug and will bei fixed as soon as possible.

**Comment by thomsmits** [comment]
Fixed with commit e700404.
