### ISSUE TITLE
Fehler in Dokumentation zum ändern der Sprache

### ISSUE THREAD

**Issue by T-Sona** [informatik-mannheim/thesis-template#28]
In der `thesis.tex` (Zeile 13) steht, dass man beim Ändern der Sprache zu Englisch, das Paket _csquotes_ folgendermaßen konfigurieren muss:

```
\usepackage[autostyle=true,english=quotes]{csquotes} 
```

Diese Konfiguration führt zu einem Fehler, da (laut [Dokumentation](https://ctan.kako-dev.de/macros/latex/contrib/csquotes/csquotes.pdf)) `quotes` kein  erlaubter Wert für english ist. Die erlaubten Werte sind: `american`, `british`

**Comment by thomsmits** [comment]
Die Sprachsettings wurden mit commit 406ad249d2f235ae88e4c0cb3b902396fe5df3c1 vereinfacht. Ab sofort gibt es nur noch eine Variable, die alle Einstellungen kontrolliert.
