### ISSUE TITLE
LyX: Fehler bei titlesec

### ISSUE THREAD

**Issue by domeix** [informatik-mannheim/thesis-template#29]
Das Package 'titlesec' erzeugt bei Verwendung mit dem KOMA-Script-Bericht ('scrreprt') folgende Fehler: '_Missing number, treated as zero._' _'Illegal unit of masure (pt inserted)._'
![grafik](https://user-images.githubusercontent.com/7372281/71680352-26540a00-2d8a-11ea-85ea-a34f820b3d51.png)

**Comment by domeix** [comment]
**Workaround:**
Folgende Zeilen in `preambel.tex` löschen
```
\usepackage[sf,bf,small]{titlesec} % Einstellungen für Überschriften     
\titlespacing{\paragraph}{0pt}{1ex}{2.0ex}     
\titlespacing{\subsubsection}{0pt}{3ex}{0.0ex}     
\titlespacing{\subsection}{0pt}{4ex}{0.2ex}
\titlespacing{\section}{0pt}{7ex}{1ex}
\titleformat*{\subsubsection}{\sffamily\itshape\bfseries\small}
\titleformat*{\paragraph}{\sffamily\bfseries\small}
```

**Comment by domeix** [comment]
Vergleiche https://tex.stackexchange.com/questions/500970/titlesec-s-update-2-10-2-%e2%86%92-2-11-caused-subparagraphs-not-working-in-scrbookclas/501176#501176

**Comment by thomsmits** [comment]
Ich kann den Fehler nicht reproduzieren: LyX Version 2.3.3, pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) auf Ubuntu 19.10.

Ich habe die thesis.lyx in LyX geladen und compiliert. Das funktioniert ohne Probleme.

In der LaTeX-Version wurde mit commit [2e25df2](https://github.com/informatik-mannheim/thesis-template/commit/2e25df2fcfd908882d06524cec67c743ddcf7239#diff-9cbf4deda51ef9c2b7243c6e36ee204a)  einige Warnungen entfernt. Helfen diese Änderungen?

**Comment by domeix** [comment]
Die Änderungen haben nichts verändert. Wahrscheinlich stimmt dann mit meiner Installation etwas nicht.. Ich nutze jetzt aber wegen der Onlineverfügbarkeit Overleaf.
