### ISSUE TITLE
LaTeX: Übersetzung Quellcodeverzeichnis nicht konsistent

### ISSUE THREAD

**Issue by DevJanis** [informatik-mannheim/thesis-template#34]
bei der deutschen Spracheinstellung werden mir im Inhaltsverzeichnis alle Verzeichnisse korrekt angezeigt:

> Abkürzungsverzeichnis
> Tabellenverzeichnis
> Abbildungsverzeichnis
> Quellcodeverzeichnis
> Literatur

die jeweiligen Kapitel sind mit Ausnahme des Quellcodeverzeichnisses auch korrekt:

> Abkürzungsverzeichnis
> Tabellenverzeichnis
> Abbildungsverzeichnis
> _Listings_
> Literatur

die deutsche Übersetzung scheint jedoch zu stimmen:

>    \newcommand{\hsmalistoftables}{Tabellenverzeichnis}%
>    \newcommand{\hsmalistoffigures}{Abbildungsverzeichnis}%
>    \newcommand{\hsmalistings}{Quellcodeverzeichnis}%
>    \newcommand{\hsmaindex}{Index}%
>    \newcommand{\hsmaabbreviations}{Abkürzungsverzeichnis}%

Wenn ich die englische Übersetzung wie folgt ändere (und die Sprache umstelle),

>    \newcommand{\hsmalistoftables}{List of Tables}%
>    \newcommand{\hsmalistoffigures}{List of Figures}%
>    _\newcommand{\hsmalistings}{Quellcodeverzeichnis}%_
>    \newcommand{\hsmaindex}{Index}%
>    \newcommand{\hsmaabbreviations}{List of Abbreviations}%

ändert sich das Inhaltsverzeichnis wie folgt:

> List of Abbreviations
> List of Tables
> List of Figures
> Quellcodeverzeichnis
> Bibliography

Die Kapitelüberschriften sind allerdings auch dann nicht konsistent:

> List of Abbreviations
> List of Tables
> List of Figures
> Listings
> Bibliography

Ich verwende Overleaf und habe die zip-Datei entsprechend der Anleitung hochgeladen und kompiliert.

**Comment by thomsmits** [comment]
Kann reproduziert werden, ist ein Bug.
