### ISSUE TITLE
Das Literaturverzeichnis wird mir nicht angezeigt.

### ISSUE THREAD

**Issue by eyuepuenlue** [informatik-mannheim/thesis-template#35]
Guten Tag Herr Smits, 

für meine BA wüde ich gerne Ihre Latex-vorlage nuten. 
Leider bekomme ich einfach kein Literaturverzeihnis angezeigt. auch wenn ich das Projekt unverändert Bauenlasse oder wenn ich Expluiziet \tableofcontents angebe, passiert da nichts. Im Text in dem ich ein Zitat auszeichne wird einfach nur der Key der Quelle angezeigt.

Viele Grüße,
Eyüp Ünlü

**Comment by eyuepuenlue** [comment]
Mache ich da etwas falsch?

**Comment by eyuepuenlue** [comment]
\pringbibliography*

**Comment by thomsmits** [comment]
Haben Sie das [Makefile ](https://github.com/informatik-mannheim/thesis-template/blob/master/latex/tex/Makefile) oder die [Batchdatei ](https://github.com/informatik-mannheim/thesis-template/blob/master/latex/create.cmd) verwendet? Falls nicht: Es ist wichtig, dass man nicht nur `pdflatex` mehrmals aufruft, sondern zwischen dem ersten und den weiteren Aufrufen `biber`.

```console
pdflatex thesis.tex
biber thesis
pdflatex thesis.tex
pdflatex thesis.tex
```

**Comment by eyuepuenlue** [comment]
Hallo Herr Smits, 

vielen Dank für die Schnelle Rückmeldung!

Ja, ich habe diese Commands in der Reheienfolge nacheinander ausgeführt, aber das hat nicht funktioniert. 
Ich habe das Terminal von IntelliJ benutzt um diese Befehle auszuführen. 
leider hat das auch nicht funktioniert. 

Wenn ich die Batchdatei manuell (mit Doppelclick) ausgefüht habe, dann wurde die Thesis vollständig(außer dem Literaturverzeichniss) erzeugt. 

Wenn ich aber in mein IntelliJ Terminal gehe und 

`START create.cmd` 

ausführe, dann wird die Datei korrekt generiert inklusive Literaturverzeichniss. 

Bei allen versuchen, die fehlgeschlagen sind, wurde mir in den logs angezeigt, dass meine literatur.bib datei leer sei.
Diese Datei war aber zu 100% nicht leer. 

Nachdem ich die Datei 3- 4 mal bearbeitet, gespeichert und compiliert habe(3 mal in der Rheinfolge), habe ich beim letzten Durchlauf diese Meldung nicht mehr bekommen. 

Ich glaube in meinem Fall war es wichtig den oben genannten Command zu benutzen und nicht die Compiler, die von IntelliJ angeboten werden. Denn die Compiler von IntelliJ compelieren die BA zwar, aber leider nun mal mit kleinen Fehlern.

Ich wünsche Ihnen einen guten Rutsch ins neue Jahr :)

Viele Grüße 

Eyüp
