### ISSUE TITLE
Snow Cards: Verschobene Card bei Verwendung optionaler Argumente

### ISSUE THREAD

**Issue by m-wagner98** [informatik-mannheim/thesis-template#36]
Verwendeter Command zur Erzeugung einer Snow Card:

```latex
\snowcard % Snowcard einbinden (Anpassungen in titelblatt.tex)  
   {F1} % Nummer des Requirements  
   {F} % Art  
   {Hoch} % Priorität  
   {User Authentifizierung} % Titel  
   {} % Herkunft (Optional)  
   {} % Konflikte (Optional)
   {Der Benutzer ist in der Lage sich über seinen Benutzernamen und sein Passwort am System anzumelden} % Beschreibung
   {Ein Benutzer kann sich mit seinem firmenweiten Benutzernamen und
   Passwort über die Anmeldemaske anmelden und hat Zugriff auf die
   Funktionen des Systems} % Fit-Kriterium (Optional)
   {} % Material (Optional) 
```

Das sieht dann im fertigen PDF (gebaut mit make) so aus:
![Bildschirmfoto vom 2022-02-12 22-39-59](https://user-images.githubusercontent.com/48804848/153729341-e4c7f232-4383-40fb-9601-4bff31c7ecce.png)

Ich würde die optionalen Felder gerne weghaben, da ich sie nicht brauche, aber ohne sieht es so aus wie im Screenshot. Das Problem tritt nicht auf, wenn ich den letzten Parameter (Material) nicht leer lasse, also zb:
{-} % Material
stattdessen verwenden würde. Ergebnis:
![image](https://user-images.githubusercontent.com/48804848/153729422-fa264133-0089-420c-a74a-28d3027cce8f.png)

Der Workaround mit dem "-" funktioniert zwar, allerdings sieht das irgendwie blöd aus.

**Comment by thomsmits** [comment]
Das Problem ist bekannt und wurde bereits mit commit c417ba3468092211b769a08eedf527061be3d5ee behoben. Wahrscheinlich haben Sie das Repo vor diesem commit gecloned oder heruntergeladen.

Bitte ersetzen Sie die Datei `titelblatt.tex` durch die [aktuelle Version](https://raw.githubusercontent.com/informatik-mannheim/thesis-template/c417ba3468092211b769a08eedf527061be3d5ee/latex/tex/titelblatt.tex). Dann sollte das Problem verschwinden.
