### ISSUE TITLE
VSCode-Unterstützung: Abkürzungsverzeichnis nicht generiert / aktualisiert

### ISSUE THREAD

**Issue by grillle** [informatik-mannheim/thesis-template#44]
### Latex-Umgebung
- MiKTeX + Strawberry Pearl
- VS Code mit Plugin "LaTeX Workshop" (v9.7.0)

getestet mit thesis-template (master-branch, Stand: 01.02.2023).

### Probleme
1. Erstmaliger Build ohne Änderungen am template laufen durch, jedoch wird **kein Abkürzungsverzeichnis** generiert
2. Erstmalige Verwendung von (neuen) Abkürzungen: Abkürzungsverzeichnis (wenn da) wird **nicht aktualisiert**

### Möglicher Fix
In *preamble.tex*: `\usepackage[acronym,symbols,toc,automake]{glossaries}`
-> Ergänzung des glossaries-Imports um **automake**

Änderungen und Neuergänzungen werden im Abkürzungsverzeichnis entsprechend angezeigt.

**Comment by thomsmits** [comment]
Das Problem kann bei VSCode reproduziert werden, tritt aber beim Bauen des Dokuments mit dem Makefile oder dem Shell-Skripten nicht auf. Es scheint so zu sein, als ob das VSCode-Plugin ein Kommando nicht aufruft, das zum Erstellen des Abkürzungsverzeichnisses notwendig ist.
Die Option `automake` können wir in das Template nicht aufnehmen, weil sie das Bauen per Kommandozeile stört.

Eine *Unterstützung von VSCode müsste einmal evaluiert* werden.
