### ISSUE TITLE
LaTeX Template in VScode

### ISSUE THREAD

**Issue by DiarSulejmani** [informatik-mannheim/thesis-template#49]
Nach dem ich die LaTex mit Vscode Anleitung aus dem Github befolgt habe kommt nach dem "Build LaTeX Project" mit Recipe: pdflatex -> biber -> makeglossaries -> pdflatex * 2 immer eine Fehler beim Build.

Die aktuellste Version des thesis-templates wurde benutzt.

LaTeX Workshop ist als Extension installiert und MiKTeX auch. Andere Studenten haben das selbe Problem.

Output des LaTeX Workshop Logs: 
![image](https://github.com/informatik-mannheim/thesis-template/assets/43576470/3190af74-059a-474e-8dbc-251bc4809394)

Output des LaTeX Compiler:
![image](https://github.com/informatik-mannheim/thesis-template/assets/43576470/f8e9dbf9-58a8-48cc-820b-0dbc8154a6ad)

Problems: 
![image](https://github.com/informatik-mannheim/thesis-template/assets/43576470/05479e7a-b732-449b-87fd-a59550a4682c)

Im Anhang die preambel.log

[preambel.log](https://github.com/informatik-mannheim/thesis-template/files/12609916/preambel.log)

**Comment by jesstein** [comment]
Das Root-Dokument ist nicht preambel.tex sondern thesis.tex. Dementsprechend sollte es auch keine preambel.log sondern thesis.log geben. Bitte versuchen Sie zunächst Thesis.tex zu kompilieren. Preamble.tex wird durch dieses Dokument geladen und kann nicht ohne einen geeigneten Rahmen ausgeführt werden.

**Comment by DiarSulejmani** [comment]
Ich habe die Thesis.tex kompiliert. Die Fehlermeldung ist beim kompilieren der Thesis.tex enstanden. Eine Thesis.log wird bei mir nicht generiert, nur die preambel.log

**Comment by jesstein** [comment]
Das Problem liegt m.E. an VSCode und insbesondere am Umgang mit Multi-File-Projekten, da die Erkennungsroutine für das Root-File nicht richtig funktioniert bzw. die Information nicht richtig gesetzt ist. Der erste Screenshot zeigt eindeutig, dass VS Code Preambel.tex als Root Dokument betrachtet. Das ist aber falsch, wie ich bereits geschrieben habe.

Ggfs. kann der Eintrag % !TEX root = relative/or/absolute/path/to/root/thesis.tex hier Abhilfe schaffen. Alternativ könnten Sie auch einen anderen Editor für Latex verwenden (z.B. TexMaker oder TexStudio) und testen, ob Sie dort Ihr Projekt kompilieren können.

**Comment by thomsmits** [comment]
Damit VSCode die `thesis.tex` als Hauptdatei erkennt, müssen Sie folgende Zeile an den Anfang in `preambel.tex` und `thesis.tex` einfügen:

```latex
% !TEX root = ./thesis.tex
```

**Comment by KoeppSebastian** [comment]
Es wäre hilfreich, wenn Sie dies in die Installationsanweisungen aufnehmen würden.

**Comment by thomsmits** [comment]
> Es wäre hilfreich, wenn Sie dies in die Installationsanweisungen aufnehmen würden.

Habe ich gemacht.
