### ISSUE TITLE
Änderung des hsmathesistype möglich?

### ISSUE THREAD

**Issue by Da-Song** [informatik-mannheim/thesis-template#61]
Ich versuche die Vorlage für eine Studienarbeit zu nutzen, die ja schon vom Umfang her sehr ähnlich der Bachelorarbeit ist. 
Leider bekomme ich den "hsmathesistype" einfach nicht geändert, wodurch statt "Studienarbeit" weiterhin "Bachelorarbeit" auf dem Deckblatt steht. Gibt es hierzu eine Lösung?

**Comment by thomsmits** [comment]
Der Titel wird in der Datei `studiengaenge.tex` gesetzt. Sie können hier einfach einen neuen Eintrag für Ihre Studienarbeit anlegen und dann in `docinfo.tex` referenzieren. Alternativ können Sie den Eintrag in `studiengaenge.tex` einfach ersetzen.

**Comment by thomsmits** [comment]
Done

**Comment by Da-Song** [comment]
Super, vielen Dank!
