### ISSUE TITLE
Fehler beim Kompilieren

### ISSUE THREAD

**Issue by BeckerMax** [informatik-mannheim/thesis-template#8]
Beim Erstellen der LaTeX-Vorlage erhalte ich einen Fehler. Der Fehler hat niedrige Priorität, da das Dokument korrekt erstellt wird, allerdings ist die Fehlermeldung störend.

Für jede \subsection erhalte ich folgenden Error. Z.B. in kapitel1.tex line 9:
```
! Missing \endcsname inserted.
<to be read again>
\numexpr
l.9 \subsection{Dritte Ebene}
The control sequence marked <to be read again> should
not appear between \csname and \endcsname.
```

Ich nutze TexMaker unter MacOS mit dem aktuellen Template von Github ohne Modifikationen.

Edit zur ersten Version: Das Auskommentieren von RedeclareSectionCommand{subsection} hilft doch nicht. Der Fehler bleibt

**Comment by thomsmits** [comment]
Der Fehler ist bekannt, liegt aber wohl nicht am Template. Bei allen Betroffenen ist er bisher verschwunden, wenn sie KomaScript aktualisiert haben. Aktualisieren Sie die LaTeX-Installation und die Pakete und probieren Sie es noch einmal.

**Comment by BeckerMax** [comment]
Nach der Aktualisierung funktioniert es. Vielen Dank.
