### ISSUE TITLE
Kopf- und Fußzeile fehlen in der LyX-Vorlage

### ISSUE THREAD

**Issue by tademeit** [informatik-mannheim/thesis-template#9]
Sehr geehrter Herr Smits, sehr geehrter Herr Gumbel,

wenn ich die LyX-Vorlage runterlade und diese in LyX auch benutze, fehlen bei mir leider die Kopf- und Fußzeilen die ich aus der LateX-Vorlage kenne komplett.

Muss ich dazu vorher eine Einstellung in LyX tätigen oder ist da ein kleiner Fehler in der Vorlage?

Gruß,
Timo Ademeit

**Comment by markusgumbel** [comment]
Hallo Herr Ademeit,

das war offenbar noch nicht richtig eingestellt. In der aktuellen Version sind nun die Überschriften sichtbar (getestet mit Lyx Version 2.2.1). Siehe Menu: Dokumente/Einstellungen/Seitenlayout/... mit Überschriften.

Viele Grüße,

Markus Gumbel

**Comment by tademeit** [comment]
Sehr geehrter Herr Gumbel,

vielen dank für die schnelle Antwort. Tatsache lag es an dieser Einstellung. Diese war statts "mit Überschriften" auf "Standard" gestellt - hat sich erledigt!

Grüße
